// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";
inline constexpr char kDisplayName[] = "FlashPilot";
inline constexpr char kVersion[] = "0.1.0";
inline constexpr std::int64_t kBuild = 1;
inline constexpr char kIdentifier[] = "site.jrtx.flashpilot";
inline constexpr char kReleaseChannel[] = "dev";

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode_Int64(std::int64_t v) { return rivet::Value(v); }

inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline std::int64_t decode_Int64(rivet::Value const& v) { if (auto p = std::get_if<std::int64_t>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Int64"); }
}  // namespace detail

struct Plan_progressEvent { std::string value; };
using Event = std::variant<Plan_progressEvent>;
inline Event decode_event(std::string const& name, rivet::Value const& value) {
  if (name == "plan-progress") return Event{Plan_progressEvent{detail::decode_String(value)}};
  throw std::runtime_error("unknown Rivet event: " + name);
}

class API {
 public:
  explicit API(rivet::windows::Backend& backend) : backend_(backend) {}

  std::future<std::string> bench_status() { auto raw = backend_.call("bench-status", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t bench_status_async(std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("bench-status", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> bench_validate() { auto raw = backend_.call("bench-validate", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t bench_validate_async(std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("bench-validate", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> dtc_read() { auto raw = backend_.call("dtc-read", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t dtc_read_async(std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("dtc-read", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> verify_plan(std::string planPath) { auto raw = backend_.call("verify-plan", rivet::Value::List{detail::encode_String(planPath)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t verify_plan_async(std::string planPath, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("verify-plan", rivet::Value::List{detail::encode_String(planPath)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

  // Shared state
  std::future<std::int64_t> get_flash_count() { auto raw = backend_.get_state("flash-count"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::int64_t { return detail::decode_Int64(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_flash_count_async(std::function<void(Result<std::int64_t>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("flash-count", [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::int64_t> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Int64(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::int64_t> set_flash_count(std::int64_t value) { auto raw = backend_.set_state("flash-count", detail::encode_Int64(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::int64_t { return detail::decode_Int64(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_flash_count_async(std::int64_t value, std::function<void(Result<std::int64_t>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("flash-count", detail::encode_Int64(value), [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::int64_t> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Int64(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::windows::Backend& backend_;
};

}  // namespace rivet_app
