// Generated by Rivet. Do not edit by hand.
import Foundation
import RivetRuntime

public enum RivetGeneratedError: Error { case typeMismatch(String); case unknownEvent(String) }
public enum RivetGeneratedConfig {
    public static let moduleName = "backend"
    public static let entryName = "start"
    public static let displayName = "FlashPilot"
    public static let version = "0.1.0"
    public static let build: Int64 = 1
    public static let identifier = "site.jrtx.flashpilot"
    public static let releaseChannel = "dev"
}

private func encode_String(_ v: String) -> RivetValue { .string(v) }
private func encode_Int64(_ v: Int64) -> RivetValue { .int64(v) }

private func decode_String(_ v: RivetValue) throws -> String { guard case .string(let x) = v else { throw RivetGeneratedError.typeMismatch("String") }; return x }
private func decode_Int64(_ v: RivetValue) throws -> Int64 { guard case .int64(let x) = v else { throw RivetGeneratedError.typeMismatch("Int64") }; return x }

public enum RivetEvent: Sendable {
    case plan_progress(String)

    public static func decode(name: String, value: RivetValue) throws -> RivetEvent {
        switch name {
        case "plan-progress": return .plan_progress(try decode_String(value))
        default: throw RivetGeneratedError.unknownEvent(name)
        }
    }
}

public struct RivetAPI: Sendable {
    public let client: RivetClient
    public init(client: RivetClient) { self.client = client }

    public func bench_status() async throws -> String {
        let result = try await client.call("bench-status", arguments: [])
        return try decode_String(result)
    }
    public func bench_validate() async throws -> String {
        let result = try await client.call("bench-validate", arguments: [])
        return try decode_String(result)
    }
    public func dtc_read() async throws -> String {
        let result = try await client.call("dtc-read", arguments: [])
        return try decode_String(result)
    }
    public func verify_plan(planPath: String) async throws -> String {
        let result = try await client.call("verify-plan", arguments: [encode_String(planPath)])
        return try decode_String(result)
    }

    // Shared state
    public func getFlash_count() async throws -> Int64 {
        let result = try await client.getState("flash-count")
        return try decode_Int64(result)
    }
    @discardableResult
    public func setFlash_count(_ value: Int64) async throws -> Int64 {
        let result = try await client.setState("flash-count", value: encode_Int64(value))
        return try decode_Int64(result)
    }
}
